baseURL = 'https://blog.yangzai.ai/'
languageCode = 'zh-cn'
title = 'ç¾Šä»”AIæ¢ç´¢'
theme = 'hugo-theme-stack'

# ç½‘ç«™å‚æ•°
[params]
  mainSections = ['post']
  rssFullContent = true
  favicon = '/favicon.ico'
  
  # æ–‡ç« é…ç½®
  [params.article]
    [params.article.image]
      enabled = true
      height = 420
      loading = "lazy"
  
  # æœç´¢é…ç½®
  [params.widgets]
    enabled = ["search"]

  [params.widgets.search]
    limit = 20
    
    [params.widgets.search.params]
      type = "fuse"
      [params.widgets.search.params.fuse]
        isCaseSensitive = false
        minMatchCharLength = 2
        findAllMatches = true
        location = 0
        distance = 100
        threshold = 0.2
        keys = ["title", "permalink", "summary", "content"]

[params.sidebar]
  emoji = 'ğŸ¥'
  subtitle = 'å¤®ä¼ç¨‹åºå‘˜ï¼ŒAIæ¢ç´¢è€…'

[params.sidebar.avatar]
  enabled = true
  local = true
  src = "img/avatar.jpg"

# èœå•é…ç½®
[[menu.main]]
  name = 'é¦–é¡µ'
  url = '/'
  weight = 1
[[menu.main]]
  name = 'æ–‡ç« '
  url = '/post'
  weight = 2
[[menu.main]]
  name = 'åˆ†ç±»'
  url = '/categories'
  weight = 3
[[menu.main]]
  name = 'æ ‡ç­¾'
  url = '/tags'
  weight = 4
[[menu.main]]
  name = 'å…³äº'
  url = '/about'
  weight = 5
[[menu.main]]
  name = 'æœç´¢'
  url = '/search'
  weight = 6

# é¡µè„šé…ç½®
[params.footer]
  since = 2024
  customText = 'ç¾Šä»”AIæ¢ç´¢'

# è¾“å‡ºé…ç½®
[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML"]
